# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
        env:
          CI: true
      - name: rsync deployments
        uses: burnett01/rsync-deployments@4.0
        with:
          switches: -avzr --delete --exclude="node_modules" --exclude="dist"
          path: /
          remote_path: ${{ secrets.TARGET }}
          remote_host: ${{ secrets.REMOTE_HOST }}
          remote_port: 22
          remote_user: ${{ secrets.REMOTE_USER }}
          remote_key: ${{ secrets.DEPLOY_KEY }}
      - name: ls -a via ssh
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: node -v
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          privateKey: ${{ secrets.DEPLOY_KEY}}
