# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
        env:
          CI: true
      - name: rsync deployments
        uses: burnett01/rsync-deployments@4.0
        with:
          switches: -avzr --delete --exclude="node_modules" --exclude="dist"
          path: /
          remote_path: ${{ secrets.TARGET }}
          remote_host: ${{ secrets.REMOTE_HOST }}
          remote_port: 22
          remote_user: ${{ secrets.REMOTE_USER }}
          remote_key: ${{ secrets.DEPLOY_KEY }}
      - name: Execute SSH commmands on remote server
        uses: JimCronqvist/action-ssh@master
        with:
          hosts: ${{ secrets.REMOTE_HOST }}
          privateKey: ${{ secrets.DEPLOY_KEY }}
          command: |
            ls -lah
            cd /home/ecolote
            # update 
            apt-get update
            # install curl 
            apt-get install curl
            # get install script and pass it to execute: 
            curl -sL https://deb.nodesource.com/setup_12.x | bash
            # and install node 
            apt-get install nodejs
            # confirm that it was successful 
            node -v
